sbt/setup-sbt@v1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,12 +1,12 @@
 name: CI
 on:
   push:
-    branches: ["main"]
-    tags: ["v*"]
+    branches: [ "main" ]
+    tags: [ "v*" ]
   pull_request:
-    branches: ["*"]
+    branches: [ "*" ]
 
-env: 
+env:
   JAVA_OPTS: -Xmx6G
 
 jobs:
@@ -14,7 +14,7 @@ jobs:
     name: CI
     strategy:
       fail-fast: false
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@v3
         with:
@@ -25,13 +25,15 @@ jobs:
         with:
           swap-size-gb: 10
 
-      - uses: coursier/cache-action@v6      
+      - uses: coursier/cache-action@v6
 
       - uses: actions/setup-java@v3
         with:
-          distribution: 'temurin' 
+          distribution: 'temurin'
           java-version: '17'
           cache: sbt
+
+      - uses: sbt/setup-sbt@v1
 
       - name: SBT remote cache
         id: remote-cache
@@ -40,8 +42,8 @@ jobs:
           path: ./.remote-cache
           key: ${{ runner.os }}-remote-cache
 
-      - name: Pull cache 
-        run: ./sbt pullRemoteCache || echo 'remote cache not found'
+      - name: Pull cache
+        run: sbt --client pullRemoteCache || echo 'remote cache not found'
 
       - name: apt-get update
         run: sudo apt-get update
@@ -53,23 +55,23 @@ jobs:
           libgirepository1.0-dev
 
       - name: Compile
-        run: ./sbt --client Test/compile
+        run: sbt --client Test/compile
 
       - name: Test
-        run: ./sbt --client test
+        run: sbt --client test
 
       - name: Publish locally
-        run: ./sbt --client publishLocal
+        run: sbt --client publishLocal
 
       - name: Build binary
-        run: ./sbt --client examples/nativeLink
+        run: sbt --client examples/nativeLink
 
-      - name: Push cache 
-        run: ./sbt --client pushRemoteCache || echo 'oh well then'
+      - name: Push cache
+        run: sbt --client pushRemoteCache || echo 'oh well then'
 
       - name: Publish ${{ github.ref }}
         if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
-        run: ./sbt ci-release
+        run: sbt --client ci-release
         env:
           PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
           PGP_SECRET: ${{ secrets.PGP_SECRET }}
@@ -77,9 +79,8 @@ jobs:
           SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
 
   mergify-build-checkpoint:
-    runs-on: ubuntu-latest
-    needs: [build]
+    runs-on: ubuntu-24.04
+    needs: [ build ]
     steps:
       - name: I only exist to please Mergify :(
         run: echo "It's a sad existence but necessary"
-
