sbt script

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,10 +33,6 @@ jobs:
           java-version: '17'
           cache: sbt
 
-
-      - name: Install sbt
-        run: sudo curl -Lo /usr/local/bin/sbt https://raw.githubusercontent.com/sbt/sbt/refs/heads/1.10.x/sbt && sudo chmod +x /usr/local/bin/sbt
-
       - name: SBT remote cache
         id: remote-cache
         uses: actions/cache@v3
@@ -45,7 +41,7 @@ jobs:
           key: ${{ runner.os }}-remote-cache
 
       - name: Pull cache 
-        run: sbt --client pullRemoteCache || echo 'remote cache not found'
+        run: ./sbt --client pullRemoteCache || echo 'remote cache not found'
 
       - name: apt-get update
         run: sudo apt-get update
@@ -57,23 +53,23 @@ jobs:
           libgirepository1.0-dev
 
       - name: Compile
-        run: sbt --client Test/compile
+        run: ./sbt --client Test/compile
 
       - name: Test
-        run: sbt --client test
+        run: ./sbt --client test
 
       - name: Publish locally
-        run: sbt --client publishLocal
+        run: ./sbt --client publishLocal
 
       - name: Build binary
-        run: sbt --client examples/nativeLink
+        run: ./sbt --client examples/nativeLink
 
       - name: Push cache 
-        run: sbt --client pushRemoteCache || echo 'oh well then'
+        run: ./sbt --client pushRemoteCache || echo 'oh well then'
 
       - name: Publish ${{ github.ref }}
         if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
-        run: sbt ci-release
+        run: ./sbt ci-release
         env:
           PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
           PGP_SECRET: ${{ secrets.PGP_SECRET }}
